//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syrian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpDaily
    {
        public int Ser { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> ExpID { get; set; }
        public Nullable<decimal> ExpVal { get; set; }
        public string Remark { get; set; }
    
        public virtual ExpList ExpList { get; set; }
    }
}
