//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syrian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orditm
    {
        public int ser { get; set; }
        public Nullable<int> ordfk { get; set; }
        public Nullable<int> itemfk { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> totval { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> shid { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<bool> ISActive { get; set; }
    
        public virtual ItmList ItmList { get; set; }
        public virtual OrdList OrdList { get; set; }
    }
}
