//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syrian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdList()
        {
            this.orditm = new HashSet<orditm>();
        }
    
        public int OrdID { get; set; }
        public Nullable<int> shitfk { get; set; }
        public string GuestName { get; set; }
        public Nullable<System.DateTime> OrdDate { get; set; }
        public Nullable<int> OrderFk { get; set; }
        public bool IsActive { get; set; }
        public string TelNum { get; set; }
        public string Address { get; set; }
        public string Mob { get; set; }
        public Nullable<bool> SyianM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orditm> orditm { get; set; }
        public virtual Shft Shft { get; set; }
    }
}
