//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syrian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExpList
    {
        public Nullable<int> ExpID { get; set; }
        public string ExpName { get; set; }
        public decimal ExpVal { get; set; }
    }
}
