//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syrian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrdList
    {
        public int OrdID { get; set; }
        public string GuestName { get; set; }
        public Nullable<int> OrderFk { get; set; }
        public Nullable<decimal> totval { get; set; }
        public Nullable<System.DateTime> OrdDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> shitfk { get; set; }
    }
}
